### ISSUE TITLE
Commodore PC-30 not booting

### ISSUE THREAD

**Issue by Altheos** [VARCem/VARCem#114]
Tested with latest build and build 1.7.2 / 1.7.0
Machine Commodore PC-30 just boots on a black screen.

**Comment by Altheos** [comment]
can be fixed with attached BIOS.txt file [bios.txt](https://github.com/VARCem/VARCem/files/5781384/bios.txt)
It will be included in a future update to the romfile.

**Comment by waltje** [comment]
Yes, thanks.

There were seeral more issues with this machine, and it has been replaced with a new machine module in v1.8.0 that includes other members of that family as well.
