### ISSUE TITLE
Can't compile latest source code

### ISSUE THREAD

**Issue by Altheos** [VARCem/VARCem#117]
I can't compile successfully dev_build current code.
It is looking for some files not existing anymore :
devices/sound/midi_mt32.c:44:10: fatal error: c_interface/c_interface.h: No such file or directory
   44 | #include <c_interface/c_interface.h>

devices/sound/midi_fluidsynth.c:55:10: fatal error: fluidsynth.h: No such file or directory
   55 | #include <fluidsynth.h>

**Comment by waltje** [comment]
I will updaye tge documentation.
Basically, all 'external' is now expected toteside in whatever $(EXTERNAL) pointdto, defaulting to ../external.
I reworked the Makefiles to reflect this
I will also upload a copy of the full set ofthose files to the website.
--waltje
Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by Altheos** [comment]
Ok. It's fixed by downloading "external" dependancies and modifying makefile : it should be external and not ../external

**Comment by waltje** [comment]
Updated BUILDING.md to include info about getting this package, and where to place it.

    On Tuesday, October 20, 2020, 6:14:15 AM EDT, Altheos <notifications@github.com> wrote:  
 
 


Ok. It's fixed by downloading "external" dependancies and modifying makefile : it should be external and not ../external

**Comment by Altheos** [comment]
Allright. Everything's fine now floowing the instructions.
