### ISSUE TITLE
[BUG] Ali1429 machines don't write to CMOS correctly

### ISSUE THREAD

**Issue by Altheos** [VARCem/VARCem#135]
Build Used : 1.7.6.1

ALI1429 machines (Olystar LIL1429 & AMI WinBIOS 486) don't seem to save setup correctly in CMOS.

To reproduce : boot an ALI1429 machine, modif setup, write CMOS and restart.
Machine should save setup but it doesn't work.
![Capture](https://user-images.githubusercontent.com/29195397/113511484-4875a280-9560-11eb-9d08-1c3a8709dcf0.JPG)

**Comment by waltje** [comment]
Fixed in #524, thanks.
