### ISSUE TITLE
[BUG] Entry point not found

### ISSUE THREAD

**Issue by Fenix770** [VARCem/VARCem#137]
I unable to start the build 524 of Varcem, because it says an entry point to DLL file is missing. 
Here is the screenshot: (it is in spanish)

![Varcem Bug](https://user-images.githubusercontent.com/31600563/114487231-9c7a2a00-9be5-11eb-9522-374e221600fd.jpg)

Also. I would like to test the NEAT chipset emulation on Varcem. Older versions of Varcem had bugs in the NEAT emulation. (#69)
(However The other Two EMS boards work flawlessly) It would be interesting, if it is complete, to port this to 86box, and obviously, if you and the 86box authors agree with this.

Thanks in advance!

**Comment by waltje** [comment]
Yes, you will need to also download the "DLL pack"  from the website,which contains the updated DLLs, including the minivhd.dll file.
> Also. I would like to test the NEAT chipset emulation on Varcem. It would be interesting,> if it is complete, to port this to 86box, and obviously, if you and the 86box authors agree> with this.They are both "managed"  by user 'greatpsycho', so they should be (at least) verysimilar already. But yes, sure, no problem here.  86Box and VARCem have alwaysexchanged a lot of code.
Regards,
Fred (waltje)

**Comment by Fenix770** [comment]
Hello.

The error appears even if all the DLL files are in the program folder:
![Varcem Error](https://user-images.githubusercontent.com/31600563/114643937-fb56a680-9cac-11eb-9877-6233fda602df.png)

**Comment by waltje** [comment]
Ouch!  I updated the DLLpack with the new "minivhd.dll" file!
Fred

    On Tuesday, April 13, 2021, 10:08:09 PM EDT, Fenix770 ***@***.***> wrote:  
 
 


Hello.

The error appears even if all the DLL files are in the program folder:

**Comment by Altheos** [comment]
This is solved and should be closed.

**Comment by waltje** [comment]
Fixed.
