### ISSUE TITLE
ATI Rage video card emulation

### ISSUE THREAD

**Issue by WhiteMagicRaven** [VARCem/VARCem#161]
The ATI Rage video card emulation is already on go
https://github.com/dingusdev/dingusppc/blob/master/devices/video/atirage.cpp

i don't know what stage it is.
It from Mac emulation
The value of Rage video card is Proprietary Graphic API 3DCIF and RAVE on Mac. Some games uses 3DCIF to enhance visuals.

**Comment by waltje** [comment]
Thanks for the heads-up!

I have looked at the code, and although it looks good structurally, I do not believe that, at this point, it is ready for porting to the VARCem project.

I did, however, clone it, and will keep an eye on its progress!

--waltje
