### ISSUE TITLE
Latest binary available (v 0.1.2) crashes when creating new disk

### ISSUE THREAD

**Issue by Altheos** [VARCem/VARCem#17]
Host : Windows 10
Guest : IBM XT286, AT Fixed disk adapter, 1 disk existing (MFM/RLL)
Creating a new disk crashes with dump : 
Exception details:
 NTSTATUS code: 0xc0000005
 Address: 0x0073BBEA 
Number of parameters: 2
Exception parameters: 0x00000000 0xFFFFFFFF

Register dump:

EIP:0x0073bbea
EAX:0x000000ff EBX:0x00000000 ECX:0x00000000 EDX:0x00000000
EBP:0x00000000 ESP:0x18f2e6a4 ESI:0x76b04090 EDI:0x000000ff

**Comment by waltje** [comment]
Hi,

I just posted new binaries on the website (2018/03/17) ... does it still happen there?

Thanks,

--waltje

--------------------------------------------
On Sat, 3/17/18, Altheos <notifications@github.com> wrote:

 Subject: [VARCem/VARCem] Latest binary available (v 0.1.2) crashes when creating new disk (#17)
 To: "VARCem/VARCem" <VARCem@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Date: Saturday, March 17, 2018, 5:31 PM
 
 Host : Windows 10
 
 Guest : IBM XT286, AT Fixed disk adapter, 1 disk existing
 (MFM/RLL)
 
 Creating a new disk crashes with dump :
 
 Exception details:
 
 NTSTATUS code: 0xc0000005
 
 Address: 0x0073BBEA
 
 Number of parameters: 2
 
 Exception parameters: 0x00000000 0xFFFFFFFF
 Register dump:
 EIP:0x0073bbea
 
 EAX:0x000000ff EBX:0x00000000 ECX:0x00000000 EDX:0x00000000
 
 EBP:0x00000000 ESP:0x18f2e6a4 ESI:0x76b04090
 EDI:0x000000ff
 
 —
 You are receiving this because you are subscribed to this
 thread.
 Reply to this email directly, view it on
 GitHub, or mute
 the thread.

**Comment by Altheos** [comment]
It still crashes with theses binaries:
Register dump:

EIP:0x0073858a
EAX:0x000000ff EBX:0x00000000 ECX:0x00000000 EDX:0x00000000
EBP:0x00000000 ESP:0x0199e6a4 ESI:0x76b04090 EDI:0x000000ff

**Comment by waltje** [comment]
I just uploaded new binaries (20180318) and tested with the OpenXT (the soon to be default machine for the emulator) and I was able to boot DOS 3.31 on A: (regular IMA file), and then create a new 360K disk on B:, using 86F as format.  Then formatted the drive with DOS, and booted the machine off of that.

Could you try again?  If it still does not work, please let us know which machine you are using..

Thanks!

**Comment by Altheos** [comment]
Thanks but it still not working. VARCem crashes at first launch whichever machine i try (including OpenXT).
Host is Windows 10 1709, Antivirus is disabled, binaries extracted to SSD folder or shared folder.
Here is a gdb backtrace if it may help you :
#0  0x0073835a in ?? ()
#1  0x74fee0bb in USER32!AddClipboardFormatListener ()
   from C:\WINDOWS\System32\user32.dll
#2  0x74ff8849 in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#3  0x00736700 in ?? ()
#4  0x74ffac8c in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#5  0x00000110 in ?? ()
#6  0x00090718 in ?? ()
#7  0x74fdbf65 in USER32!GetKeyState () from C:\WINDOWS\System32\user32.dll
#8  0x74fdbe45 in USER32!GetKeyState () from C:\WINDOWS\System32\user32.dll
#9  0x74fee0bb in USER32!AddClipboardFormatListener ()
   from C:\WINDOWS\System32\user32.dll
#10 0x74ff8849 in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#11 0x74fdbe20 in USER32!GetKeyState () from C:\WINDOWS\System32\user32.dll
#12 0x74ffb145 in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#13 0x00000110 in ?? ()
#14 0x00090718 in ?? ()
#15 0x74ffa89c in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#16 0xbb84fc30 in ?? ()
#17 0x00007ffd in ?? ()
#18 0x00000110 in ?? ()
#19 0x00090718 in ?? ()
#20 0x75005b67 in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#21 0x045db390 in ?? ()
#22 0x75006533 in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#23 0x00400000 in ?? ()
#24 0x74fe6a22 in USER32!DialogBoxIndirectParamAorW ()
   from C:\WINDOWS\System32\user32.dll
#25 0x7503bc05 in USER32!DialogBoxParamW ()
   from C:\WINDOWS\System32\user32.dll
#26 0x0073385f in ?? ()
#27 0x74fee0bb in USER32!AddClipboardFormatListener ()
   from C:\WINDOWS\System32\user32.dll
#28 0x74ff8849 in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#29 0x007333e0 in ?? ()
#30 0x74ffacd3 in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#31 0x00000111 in ?? ()
#32 0x0000046c in ?? ()
#33 0x001706a0 in ?? ()
#34 0x74fdbf65 in USER32!GetKeyState () from C:\WINDOWS\System32\user32.dll
#35 0x74fdbe45 in USER32!GetKeyState () from C:\WINDOWS\System32\user32.dll
#36 0x74fee0bb in USER32!AddClipboardFormatListener ()
   from C:\WINDOWS\System32\user32.dll
#37 0x74ff8849 in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#38 0x74fdbe20 in USER32!GetKeyState () from C:\WINDOWS\System32\user32.dll
#39 0x74ffb145 in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#40 0x00000111 in ?? ()
#41 0x0000046c in ?? ()
#42 0x001706a0 in ?? ()
#43 0x74ffa89c in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#44 0xbb84fc30 in ?? ()
#45 0x00007ffd in ?? ()
#46 0x00000111 in ?? ()
#47 0x0000046c in ?? ()
#48 0x001706a0 in ?? ()
#49 0x74fdb95b in USER32!SendMessageW () from C:\WINDOWS\System32\user32.dll
#50 0x73d06934 in CreateMappedBitmap ()
   from C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.16299.309_none_5d7d0b9ba7da9417\comctl32.dll
#51 0x73d1c14b in ImageList_GetIconSize ()
   from C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.16299.309_none_5d7d0b9ba7da9417\comctl32.dll
#52 0x74fee0bb in USER32!AddClipboardFormatListener ()
   from C:\WINDOWS\System32\user32.dll
#53 0x74ff8849 in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#54 0x73d1b890 in ImageList_GetIconSize ()
   from C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.16299.309_none_5d7d0b9ba7da9417\comctl32.dll
#55 0x74ffb145 in USER32!EndTask () from C:\WINDOWS\System32\user32.dll
#56 0x00000202 in ?? ()
#57 0x00000000 in ?? ()

**Comment by Altheos** [comment]
Own compiled build on host cpu (i5-3570) works fine : make -j4 -f Makefile.local

**Comment by waltje** [comment]
Finally found the issue, and worked around it. It seems to work OK now.
