### ISSUE TITLE
Can't attach MFM Hard Disk

### ISSUE THREAD

**Issue by Altheos** [VARCem/VARCem#24]
Hi,
I can't make MFM Hard drive works with IBM XT286.
Hard Drive is configured with diagnostic disc but does not appear when restart.
Works on 86Box.

Config :
[Machine]
machine = ibm_xt286
mem_size = 640
cpu_use_dynarec = 0
enable_sync = 0
[Other peripherals]
hdc = mfm_at
[Hard disks]
hdd_01_parameters = 17, 6, 615, 0, mfm
hdd_01_mfm_channel = 0

**Comment by waltje** [comment]
Fixed in the next commit.
