### ISSUE TITLE
When memory is bigger than accepted by machine malloc corrupts.

### ISSUE THREAD

**Issue by claunia** [VARCem/VARCem#25]
Issue: When memory is bigger than accepted by machine, malloc corrupts and segfaults.
Configuration:
```
[Machine]
machine = ibm_pc
mem_size = 32768
```

Expected behaviour: Fail gracefully informing user of incorrect configuration or automatically reduce memory to maximum allowed.

**Comment by waltje** [comment]
Fixed.
