### ISSUE TITLE
Can't boot MFM Hard drive with XT286

### ISSUE THREAD

**Issue by Altheos** [VARCem/VARCem#27]
Error "Bad or missing Command Interpreter" when booting. Tested with PCDOS 3.3 and MSDOS 5 on latest build.
Config used : 
IBM XT286, 640 kb, HDD Type 2 (20 Mb MFM 615/4/17)

**Comment by ppgrainbow** [comment]
I can boot the XT286 just fine! You probably forgot to place the COMMAND.COM file in the root directory of drive C.

My config used:
IMB XT 286, EGA, 1.63 MB RAM (640 KB base, 1 MB XMS), HDD Type 3 (30 MB MFM 615/6/17), MS-DOS 3.3

**Comment by Altheos** [comment]
Not a command.com problem, the drive was formatted with /S switch.
And the same disk is working with 86Box.

**Comment by ppgrainbow** [comment]
That's odd...

**Comment by Altheos** [comment]
Solved with latest revision.
