### ISSUE TITLE
use sizeof operator for a pointer type expression.

### ISSUE THREAD

**Issue by 360CodeSafe** [VARCem/VARCem#49]
Hi all,

There is a 'sizeof' issue found by Qihoo360 CodeSafe Team.

https://github.com/VARCem/VARCem/blob/eb1de7d3260d08248a0c04770117c1569f7779d2/src/devices/cdrom/cdrom.c#L2285

the sub expression of operator size 'gesn_event_header' is a pointer type.
Do we really need a size of a pointer here or should it be actually the size of the type which is pointed by the pointer (as line 2333)?

**Comment by waltje** [comment]
Correct.  Was already changed in the new code:

    typedef struct { .... } gesn_xxx_t;

    static gesn_xxx_t *gesn_xxx;

and then a sizeof the type, not the pointer.

Updated the mainline code as well, thanks.

BTW, please contact me on the IRC channel, or by email!
