### ISSUE TITLE
return an uninitialized value?

### ISSUE THREAD

**Issue by 360CodeSafe** [VARCem/VARCem#50]
Hi all,

There is an uninitialized return value by Qihoo360 CodeSafe Team.

https://github.com/VARCem/VARCem/blob/eb1de7d3260d08248a0c04770117c1569f7779d2/src/devices/scsi/scsi_bus.c#L88
int variable 'len' is declared without initialized, in line 93 to line 95, some if branches set value for 'len'.
Is that enough for all the possibility the value of 'group' could be? Maybe there is still a risk that the value of 'len' may be uninitialized. Could it be set a value (like 0) when it is declared?

Cheers
Qihoo360 CodeSafe Team

**Comment by 360CodeSafe** [comment]
the same situation as the value 'temp' in file 'src/devices/video/vid_sdac_ramdac.c':
https://github.com/VARCem/VARCem/blob/eb1de7d3260d08248a0c04770117c1569f7779d2/src/devices/video/vid_sdac_ramdac.c#L141

**Comment by waltje** [comment]
The scsi_bus.c file is no longer used (or present) in the new code, but yes, in the current code, that could end up being a problem, if we get a command from groups 3, 4 or 7.

Confirmed bug in vid_sdac_ramdac.c - fixed, thanks!
