### ISSUE TITLE
Extraneous character in intel4x0.c

### ISSUE THREAD

**Issue by MoochMcGee** [VARCem/VARCem#78]
The \ at the end of this line isn't supposed to be there.

https://github.com/VARCem/VARCem/blob/b290ba1e80711badb862dc72eff300e3c96054ed/src/devices/chipsets/intel4x0.c#L338

**Comment by waltje** [comment]
It is called a 'line continuation marker', aka "more on next line".  Standard C.

**Comment by MoochMcGee** [comment]
Yeah but it's simply not needed here, as this code isn't in a macro. This just mildly obfuscates the code to someone who's not used to this syntax outside of macros.
