### ISSUE TITLE
XTIDE not working

### ISSUE THREAD

**Issue by jvernet** [VARCem/VARCem#80]
I'm trying to use XTIDE with Amstrad PC 1640 emulation. I do not have any HD icon showing and no boot on HD.

I have roms in doms/disk/Xtide...

**Comment by waltje** [comment]
Hi,

Please email your config file to waltje@varcem.com so I can have a look.

Thanks,

Fred
__
Sent from my Samsung Note4 LTE smartphone


-------- Original message --------

**Comment by jvernet** [comment]
Here is the file.
Another issue: if i use ST506emuation, any size of disk always finish in a 13Mb formatted disk...
[pc1640.zip](https://github.com/VARCem/VARCem/files/3227992/pc1640.zip)

**Comment by waltje** [comment]
Bug #80 fixed in build 412 - thanks for reporting it!

The standard IBM-PC St506 disk controller understood only 10M and 20M disks, using jumper settings on the controller.  More choices coming up in v1.7.2 (these exist in 1.7.1, but are not 100% OK yet.)
